Notebook server validation
StatCan/jupyter-apis pull request #19
Opened 2020-09-08 18:20 UTC by saffaalvi

Resolves https://github.com/StatCan/jupyter-apis/issues/7

2020-09-14 16:04 UTC, zachomedia approved these changes
Assuming this has been tested, this LGTM!

2020-09-14 20:07 UTC, brendangadd commented
Converting to draft; I want to push something to this before it merges.

2020-09-16 02:24 UTC, brendangadd requested changes
Form accepts raw numbers for RAM as valid which, defaulting to Mi, allows values outside the valid range.

2020-09-16 17:56 UTC, brendangadd approved these changes

2020-09-16 17:57 UTC, merged