feat: add KF_LANG env variable
StatCan/jupyter-apis pull request #48
Opened 2020-12-17 15:38 UTC by wg102

Resolves https://github.com/StatCan/jupyter-apis/issues/47

2021-01-06 17:24 UTC, Ito-Matsuda requested changes
Unsure if the following files also need to be modified to also have a field for language; [types.ts](https://github.com/StatCan/jupyter-apis/blob/feat-env-var/frontend/src/app/utils/types.ts) and [spawner_ui_config.yaml](https://github.com/StatCan/jupyter-apis/blob/feat-env-var/samples/spawner_ui_config.yaml). Only found those two files after searching with `shm` through this project.  The `spawner_ui_config` seems to set defaults and if it's read only, but the code works just fine without it (set elsewhere). As for `types.ts` I have a feeling it _might_ (make note of italics im not 100% sure) need to be in there somewhere.  I'm not super familiar with jupyter-apis but searching [import { Config } ](https://github.com/StatCan/jupyter-apis/search?q=import+%7B+Config+%7D) produces some results where the `Config` interface definition is used.

2021-01-06 20:01 UTC, wg102 commented on notebooks.go
> +	Language		   string			 `json:"language"`
This was due to using tabs instead of spaces

2021-01-15 16:24 UTC, Ito-Matsuda reviewed
Looks fine to me. Right now `shm` defaults to True/Enabled, but you mentioned that the change there needs to take place in the manifest.

2021-01-15 16:29 UTC, brendangadd requested changes
**Commit message:**
* Make title describe the feature rather than the variable
* Add a message body that provides some details on what you changed

2021-01-15 16:29 UTC, brendangadd commented on notebooks.go
> +	match, err := regexp.MatchString("[[:alpha:]]{2}(_[[:alpha:]]{2})?$", req.Language)
Matches anything that **ends** with a valid code. Needs a `^` in there.

2021-01-15 16:29 UTC, brendangadd commented on notebooks.go
> +const EnvKFLanguage string = "KF_LANG"
Treat acronyms in variable names as regular words for camelcasing.

2021-01-15 16:29 UTC, brendangadd commented on notebooks.go
> +			var errLanguageFormat = errors.New("Error server language format")
Make error message more clear, so someone reading logs in a console is likely to understand what occurred.

2021-01-15 16:29 UTC, brendangadd commented on frontend/src/assets/i18n/fr.json
> +    "lblSystemLanguage":"Language du système",
"Langue"?

2021-01-21 17:31 UTC, brendangadd commented
@wg102 Looks great, and commit message is excellent. You can squash it down (keep the new commit message) and we'll merge.

2021-01-21 17:42 UTC, merged